### ISSUE TITLE
General: Breakage - Pagination "Prev" arrow was broken

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#108]
![general - 13](https://cloud.githubusercontent.com/assets/12888048/8974339/3239cf22-36a3-11e5-8e6e-c11dc951e8b8.jpg)

**Comment by genesiscebudigital** [comment]
Hi, it's ok in my end . , try to remove cache

**Comment by romatitan** [comment]
Hi,
I already clear the cache.
This issue still reproducible in gallery page.
