### ISSUE TITLE
General: Incorrect link but display the an existing inner page(s)

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#111]
Step to Reproduce
1.Go to a ANY inner page(s).
e.g http://primeliquidation.stage.titanweb.com.au/special/

2. Input or type any numbers after the url of the page
e.g http://primeliquidation.stage.titanweb.com.au/special/3216346

3. Observe that, it still displays the "special page" but this time, it has number included in the url

It should display the "Page Not Found" instead.

![general - 14](https://cloud.githubusercontent.com/assets/12888048/9002080/5c8ab5e4-3792-11e5-9cb9-21c058b96856.jpg)

**Comment by genesiscebudigital** [comment]
this is not a bug . , please try the other titan website and add any numbers . ,
