### ISSUE TITLE
Font-color for "No image were found" should be different from the page description, to be distinguished it as not part of the description and it is an info/expression message. 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#113]
![gallery - 08](https://cloud.githubusercontent.com/assets/12888048/9002219/d19bb0c6-3793-11e5-8236-a85626c5e1cd.jpg)

**Comment by genesiscebudigital** [comment]
it's ok . , it will not affect the design . , as long as the functionality works

**Comment by romatitan** [comment]
Enhancement not applied.
