### ISSUE TITLE
Homepage: The color used for the Magnifier icon background was set to rgb (51, 122, 183). It should be rgb (9, 38, 58).

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#12]
Screenshot(s):
![homepage - 05](https://cloud.githubusercontent.com/assets/12888048/8447023/ea8aba8a-1fe4-11e5-9a4e-f127c0c4bbd7.jpg)

**Comment by genesiscebudigital** [comment]
I just slice the Magnifier icon from psd. , thats it
