### ISSUE TITLE
Gallery: Breakage - the page did not display the images in the album

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#121]
![gallery - 09](https://cloud.githubusercontent.com/assets/12888048/9101619/bc5c1a0c-3c1b-11e5-9098-c10cbd9b3525.jpg)

**Comment by romatitan** [comment]
Hi,
Again, the page did not display the images in the album.
After clicking the album, the page load, then it just goes back to the gallery page.

**Comment by genesiscebudigital** [comment]
It's ok now . ,remove cache . , thanks
