### ISSUE TITLE
Homepage: There's a white blank space below the footer.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#124]
![homepage - 24](https://cloud.githubusercontent.com/assets/12888048/9103400/98a175de-3c30-11e5-975c-f6ad54561b9a.jpg)

**Comment by genesiscebudigital** [comment]
please provide screenshot . , I did not see the white blank space in the footer

**Comment by genesiscebudigital** [comment]
I remove the white space so that it is consistent to the other pages

**Comment by romatitan** [comment]
The white space was still there.
