### ISSUE TITLE
Default no-image should use a light+grayscale version of the client's logo.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#16]
Screenshot(s):
![homepage - 09](https://cloud.githubusercontent.com/assets/12888048/8447389/5d0f4dbe-1fea-11e5-8d14-276288c880bd.jpg)

**Comment by romatitan** [comment]
Default no-image should use a light+grayscale version of the client's logo.

![image](https://cloud.githubusercontent.com/assets/12888048/8612878/865b7b44-270a-11e5-9ede-0bcbca41b124.jpg)

**Comment by genesiscebudigital** [comment]
this is a gray scale from photoshop . ,
