### ISSUE TITLE
Project Scope: Pagination is not supported for Woocommerce (product) category

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#33]
Please update project scope. Thanks.
Screenshot(s):
![project scope - 01](https://cloud.githubusercontent.com/assets/12888048/8450675/a6687b5a-200f-11e5-8bcd-bd255818e4e9.jpg)

**Comment by genesiscebudigital** [comment]
that is a summarize of what is inside the our product page.
