### ISSUE TITLE
Project Scope: Displaying "price" for Product Category is not supported.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#34]
Please update the scope accordingly. Thanks.

Screenshot(s):
![project scope - 02](https://cloud.githubusercontent.com/assets/12888048/8450954/f39e9ef2-2011-11e5-9b05-b485382536b2.jpg)

**Comment by genesiscebudigital** [comment]
It does not mean Product Category must display price.
it  mean our product page has
1. product category
2. product thumbnails with price
3. fancybox on click magnifying glass
4. paginate if more than 16

**Comment by romatitan** [comment]
If the price should not be displayed on Our Products page, then it should not be included in the project scope - Our Product section to avoid confusion.
![project scope - 03](https://cloud.githubusercontent.com/assets/12888048/8562610/5f5c6a44-2566-11e5-8a94-c64dc8fbcd13.jpg)


If the Product page should have and display the ff as you have said,
"1. product category
2. product thumbnails with price
3. fancybox on click magnifying glass
4. paginate if more than 16"
Then, where's the "2. product thumbnails with price"  in product page?
I guess its for "Product Single" and not on "Our Products" page.

To be able to check if the project meets the standard and specification, 
the project scope should be accurate as well.
Please update the scope accordingly. Thanks.
