### ISSUE TITLE
Product & Product Single: Shadow effect on the right and left border of the image container differs from what the design has.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#37]
Screenshot(s):
![product - 05](https://cloud.githubusercontent.com/assets/12888048/8451280/ba723122-2014-11e5-8b00-ffc1ee9338b2.jpg)

**Comment by genesiscebudigital** [comment]
i just copy the color border color from the design

**Comment by genesiscebudigital** [comment]
the border color is not consitent in the psd . ,

**Comment by romatitan** [comment]
Clarification:  What should be the layout/style for featured / product image(s).
In the design, some images have,
1. right side with red border and its left side don't have but still can distinguish its left border.
2. both sides have red borders
3. left side of the image totally don't have a border

Here's the screenshot from the given design.
![general - 05](https://cloud.githubusercontent.com/assets/12888048/8693101/f76c3d3c-2b06-11e5-8e93-7441c7926014.jpg)


Affected page: Homepage, Our Products, Product Sub Category, Product Single as well as the News and News single page images.

**Comment by genesiscebudigital** [comment]
yes . , much better if we put consistent border in the image

**Comment by romatitan** [comment]
Product image(s) should have consistent borders.
![general - 12](https://cloud.githubusercontent.com/assets/12888048/8841851/96cdec6c-3125-11e5-93ec-b1ff9f273341.jpg)

HOMEPAGE
![general - 08](https://cloud.githubusercontent.com/assets/12888048/8841852/96ce9f0e-3125-11e5-8b24-37b7b6fef7db.jpg)

PRODUCT SINGLE PAGE
![general - 09](https://cloud.githubusercontent.com/assets/12888048/8841853/96cef3be-3125-11e5-87e2-84252be17ccf.jpg)

PRODUCT SUB CATEGORY PAGE
![general - 10](https://cloud.githubusercontent.com/assets/12888048/8841855/96cf83ba-3125-11e5-947f-4c1a95831f01.jpg)

OUR PRODUCTS PAGE
![general - 11](https://cloud.githubusercontent.com/assets/12888048/8841854/96cf4d46-3125-11e5-8913-469390ced4f0.jpg)

**Comment by genesiscebudigital** [comment]
I use the same border color for all images
![border](https://cloud.githubusercontent.com/assets/11186352/8867103/c40c2fd6-31f7-11e5-8a58-b97c21eafaa7.png)

**Comment by romatitan** [comment]
Verified fixed.
