### ISSUE TITLE
Clarification: There's a conflict between the project scope and its implementation with the "Enquire Now" button in Product Single page

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#41]
Summary:
Once click the "Enquire Now" button in Product Single page, it will open a modal form and not redirect to Contact Us which stated in the project scope.

Please update the scope accordingly. Thanks

Screenshot(s):
![product single - 15](https://cloud.githubusercontent.com/assets/12888048/8468055/3635fcce-2099-11e5-9d84-2a7f1683f57e.jpg)

**Comment by romatitan** [comment]
Please provide comment(s). Thanks

**Comment by genesiscebudigital** [comment]
the design brief is direct to contact us . , i will redirect it
