### ISSUE TITLE
Homepage: Font, font-size and font-weight for Featured Products title differs from the design

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#5]
URL: http://primeliquidation.stage.titanweb.com.au/
Summary:
The font used for the "Featured Products" title was Roboto.
Its font-size was set to 32px and font-weight of 500.
The font should be OpenSans, a font-size of 34px and font-weight of Semibold or 600.

Screenshot(s):
![homepage - 02](https://cloud.githubusercontent.com/assets/12888048/8427589/1f17f91a-1f4b-11e5-87b1-95504c6e1d69.jpg)

**Comment by genesiscebudigital** [comment]
Please look at the psd again and don't click the featured products label

**Comment by romatitan** [comment]
The font size should be 34px.
![homepage - 15](https://cloud.githubusercontent.com/assets/12888048/8613205/c9df4f18-270e-11e5-9b43-e2c5a5ab82b4.jpg)
