### ISSUE TITLE
Homepage: There's no indention provided for "Featured Products" title.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#6]
URL: http://primeliquidation.stage.titanweb.com.au/
Screenshot(s): 
![homepage - 03](https://cloud.githubusercontent.com/assets/12888048/8427679/d2dd2628-1f4b-11e5-9b8e-a8966dc1147d.jpg)

**Comment by genesiscebudigital** [comment]
Please look at the psd again and don't click the featured products label
