### ISSUE TITLE
Product Single: After closing the  fancy box, the  magnifying glass icon still shows or appears in active state.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#71]
Affected device(s): iPad Air

Screenshot(s):
![product single - 20](https://cloud.githubusercontent.com/assets/12888048/8474688/7afd7986-20e4-11e5-8347-d55a792064da.jpg)

**Comment by genesiscebudigital** [comment]
this is not part of the psd layout

**Comment by romatitan** [comment]
After closing the fancy box, it will show the magnifying glass icon in red color, then changed back to dark blue color.
