### ISSUE TITLE
Question: What should be the consistent layout arrangement of the sidebar.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#74]
Summary:
Inconsistent Sidebar layout arrangement.
Other pages don't have spaces between footer and sidebar container, others do have.

Screenshot(s):
![sidebar - 04](https://cloud.githubusercontent.com/assets/12888048/8491508/d7550a7c-216c-11e5-91d4-576a7e99fecf.jpg)
![sidebar - 03](https://cloud.githubusercontent.com/assets/12888048/8491509/d757b240-216c-11e5-8b08-17ce852ea2a1.jpg)

**Comment by romatitan** [comment]
Please provide comment. Thanks.

**Comment by genesiscebudigital** [comment]
much better if we will remove the white space above the footer
