### ISSUE TITLE
Sidebar: Roboto font was used for the Product category list. It should be Myriad Pro.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#8]
Screenshot(s):
![sidebar - 01](https://cloud.githubusercontent.com/assets/12888048/8428126/e7528d98-1f4e-11e5-86fc-c2f402e675b8.jpg)

**Comment by genesiscebudigital** [comment]
myriad pro font is block listed

**Comment by romatitan** [comment]
The font was changed to "Open Sans".
