### ISSUE TITLE
Special: There's no space between the image and the page border.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#82]
Affected browser: Firefox, IE 11,10,9
Screenshot(s):
![special - 03](https://cloud.githubusercontent.com/assets/12888048/8614310/06c6703a-271b-11e5-9c53-85c66a573877.jpg)

**Comment by romatitan** [comment]
This issue still exists in Firefox and IE.
Breakage on Chrome and Opera browser.

Design: Special Page
![02-pri-specials](https://cloud.githubusercontent.com/assets/12888048/8691978/0900d342-2afc-11e5-9703-da0780dabd14.jpg)

**Comment by genesiscebudigital** [comment]
it's ok in my end . ,try to clear cache

**Comment by romatitan** [comment]
Hi,

This issue still exists.
I've already cleared the cache of my browser, and even reproduce this issue in another computer.
