### ISSUE TITLE
Header: Facebook icon background color was set to rgb (51, 122, 183). It should be rgb (121, 160, 187).

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#9]
Screenshot(s):
![header - 01](https://cloud.githubusercontent.com/assets/12888048/8446777/bdb0c11a-1fe1-11e5-9d18-ed8039f552ee.jpg)

**Comment by genesiscebudigital** [comment]
I just slice the fb icon from psd
