### ISSUE TITLE
Homepage content was hidden even without clicking the "Read Less" button.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Prime-Liquidation#96]
Error occurs on devices.

Step to replicate:
A.
1. Portrait View, Click the "Read More" button in the homepage content
2. Scroll down and observe that the homepage content was hidden even without clicking the "Read Less" button.

B
1.Portrait View, Click the "Read More" button in the homepage content
2. Rotate the device from portrait to landscape view.
3. Observe that the homepage content was hidden even without clicking the "Read Less" button.

Landscape View
![homepage - 20](https://cloud.githubusercontent.com/assets/12888048/8868237/14a5f002-3208-11e5-9db2-0517f6ee190d.jpg)

Portrait View
![homepage - 19](https://cloud.githubusercontent.com/assets/12888048/8868238/14b15d84-3208-11e5-9647-b162aaea483f.jpg)

**Comment by romatitan** [comment]
Issue still reproducible.
Try to scroll down and up as well.

**Comment by genesiscebudigital** [comment]
Hi, Try to clear cache . ,thanks

**Comment by romatitan** [comment]
Verified fixed. Thanks.
